// Icons for the application
// Re-export icons from Element Plus and local Heroicons

// Element Plus Icons (verified to exist)
import {
  Plus,
  Clock,
  Calendar,
  Check,
  CircleCheck,
  CirclePlus,
  CopyDocument,
  Delete,
  Download,
  Edit,
  Folder,
  Link,
  List,
  Refresh,
  Search,
  Upload,
  User,
  VideoPlay,
} from '@element-plus/icons-vue'

// Local Heroicons (not available in @element-plus/icons-vue)
import {
  Plus as PlusEl,
  ArrowsRightLeft,
  DocumentDuplicate,
  ChartBar,
  PuzzlePiece,
  Clock as ClockEl,
  Calendar as CalendarEl,
  QueueList,
  CheckCircle,
  XCircle,
  ExclamationTriangle,
  ExclamationCircle,
  InformationCircle,
  ArrowsCircular,
  Envelope,
  Home,
  Cog,
  Users,
  UserCircle,
  ShieldCheck,
  ClipboardDocumentList,
  Cog8Tooth,
  DocumentChartBar,
  Play,
  Link as LinkEl,
  ChartNoDataIcon,
  TrendingUp,
  TrendingDown,
  Minus,
} from './Heroicons'

// Re-export all
export {
  // Element Plus
  Plus,
  Clock,
  Calendar,
  Check,
  CircleCheck,
  CirclePlus,
  CopyDocument,
  Delete,
  Download,
  Edit,
  Folder,
  Link,
  List,
  Refresh as RefreshRight,
  Search,
  Upload,
  User,
  VideoPlay,
  // Local Heroicons
  PlusEl,
  ArrowsRightLeft,
  DocumentDuplicate,
  ChartBar,
  PuzzlePiece,
  ClockEl,
  CalendarEl,
  QueueList,
  CheckCircle,
  XCircle,
  ExclamationTriangle,
  ExclamationCircle,
  InformationCircle,
  ArrowsCircular,
  Envelope,
  Home,
  Cog,
  Users,
  UserCircle,
  ShieldCheck,
  ClipboardDocumentList,
  Cog8Tooth,
  DocumentChartBar,
  Play,
  LinkEl,
  ChartNoDataIcon,
  TrendingUp,
  TrendingDown,
  Minus,
  // Alias exports
  Plus as PlusIcon,
  ArrowsRightLeft as ArrowsRightLeftIcon,
  DocumentDuplicate as TemplateIcon,
  ChartBar as ChartBarIcon,
  PuzzlePiece as PuzzleIcon,
  ClockEl as ClockIcon,
  CalendarEl as CalendarIcon,
  QueueList as QueueListIcon,
  CheckCircle as CheckCircleIcon,
  XCircle as XCircleIcon,
  ExclamationTriangle as ExclamationTriangleIcon,
  ExclamationCircle as ExclamationCircleIcon,
  InformationCircle as InformationCircleIcon,
  ArrowsCircular as ArrowPathIcon,
  Envelope as EnvelopeIcon,
  Home as HomeIcon,
  Cog as CogIcon,
  Users as UsersIcon,
  UserCircle as UserCircleIcon,
  ShieldCheck as ShieldCheckIcon,
  ClipboardDocumentList as ClipboardDocumentListIcon,
  Cog8Tooth as Cog8ToothIcon,
  DocumentChartBar as DocumentChartBarIcon,
  Play as PlayIcon,
  LinkEl as LinkIcon,
  ChartNoDataIcon as NoDataIcon,
  Folder as FolderIcon,
}
